# Generated by Django 5.1 on 2024-10-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_remove_message_recaptcha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='mini_about',
            field=models.TextField(blank=True, default='Al-baraa Al-sadeq', null=True),
        ),
    ]
