# Generated by Django 5.1 on 2024-10-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_alter_information_mini_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='mini_about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
